# version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: alx
    restart: always
    environment:
      POSTGRES_USER: alx
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: alx
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: